apiVersion: v1
kind: Service
metadata:
  name: mail-server
  labels:
    product: shared
    environment: development
    role: server
    image: mail-service
    version: 1.0.0
    app: mail-server
    release: stable
spec:
  type: ClusterIP
  selector:
    mail.dev/role: server
    release: stable
  ports:
    - name: https
      port: 443
      targetPort: 4000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
