apiVersion: v1
kind: Service
metadata:
  name: subscription-server
  labels:
    product: shared
    environment: production
    role: server
    image: subscription-service
    version: 0.16.0
    app: subscription-server
    release: stable
spec:
  type: ClusterIP
  selector:
    subscription.prod/role: server
    release: stable
  ports:
    - name: https
      port: 443
      targetPort: 4000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
