version: '3.5'
services:
  node:
    tty: true
    stdin_open: true
    container_name: subscription-service
    env_file:
      - ./.env
    depends_on:
      - mongo
    build:
      context: .
      target: deps
    networks:
      - subscription-system
    ports:
      - ${PORT}:${PORT}
      - '39812:4040'
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'

  mongo:
    image: 'mongo:3.6'
    networks:
      - subscription-system

networks:
  subscription-system:
    name: subscription-system
