version: '3.5'
services:
  node:
    tty: true
    stdin_open: true
    container_name: mail-service
    env_file:
      - ./.env
    build:
      context: .
      target: deps
    networks:
      - subscription-system
    ports:
      - ${PORT}:${PORT}
      - '39813:4050'
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'

networks:
  subscription-system:
    name: subscription-system
